spring:
  application:
    name: eureka-server

server:
  port: 100

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: util://${eureka.instance.hostname}:${server.port}/eureka/
